graph LR
  x3d474db92cf09724>"mensaje"]:::outdated ==> xc5ec810879cc40ee>"recorte"]:::outdated
    x3d474db92cf09724>"mensaje"]:::outdated ==> x32cb0d977e75588d>"elimino"]:::outdated
    x3d474db92cf09724>"mensaje"]:::outdated ==> x0dc39fa9e42347ba>"reflectancia"]:::outdated
    x3d474db92cf09724>"mensaje"]:::outdated ==> x0e71b645b3e50d0c>"script_descarga_py"]:::outdated
    x3d474db92cf09724>"mensaje"]:::outdated ==> x70dd0adf732b9ac4>"estado_descarga"]:::outdated
    xfabd587be49f2fed>"fecha"]:::outdated ==> x0dc39fa9e42347ba>"reflectancia"]:::outdated
    xfabd587be49f2fed>"fecha"]:::outdated ==> x38637a02f9b83fc8>"lab"]:::outdated
    x0e71b645b3e50d0c>"script_descarga_py"]:::outdated ==> x70dd0adf732b9ac4>"estado_descarga"]:::outdated
    x2eb57580dd338e28(["excel"]):::outdated ==> x1a91c1978c7a143b(["datos_lab"]):::outdated
    x38637a02f9b83fc8>"lab"]:::outdated ==> x1a91c1978c7a143b(["datos_lab"]):::outdated
    x3975d57dc4a04f5c>"descarga"]:::outdated ==> x0a08cea06a6d211f(["producto_zip"]):::outdated
    xe56f95f4237d1e66(["script_py"]):::outdated ==> x0a08cea06a6d211f(["producto_zip"]):::outdated
    xd2e55a6b497fb062(["fecha_descarga"]):::outdated ==> x4b150ba8dbe4203d(["recorte_tif"]):::outdated
    x0a08cea06a6d211f(["producto_zip"]):::outdated ==> x4b150ba8dbe4203d(["recorte_tif"]):::outdated
    xc5ec810879cc40ee>"recorte"]:::outdated ==> x4b150ba8dbe4203d(["recorte_tif"]):::outdated
    x29bd13377b9e6171>"archivo_excel"]:::outdated ==> x2eb57580dd338e28(["excel"]):::outdated
    x2eb57580dd338e28(["excel"]):::outdated ==> xd2e55a6b497fb062(["fecha_descarga"]):::outdated
    xfabd587be49f2fed>"fecha"]:::outdated ==> xd2e55a6b497fb062(["fecha_descarga"]):::outdated
    xd2e55a6b497fb062(["fecha_descarga"]):::outdated ==> xe56f95f4237d1e66(["script_py"]):::outdated
    x0e71b645b3e50d0c>"script_descarga_py"]:::outdated ==> xe56f95f4237d1e66(["script_py"]):::outdated
    x2eb57580dd338e28(["excel"]):::outdated ==> x75ae8feee719d1e2(["datos_gis"]):::outdated
    xd2e55a6b497fb062(["fecha_descarga"]):::outdated ==> x75ae8feee719d1e2(["datos_gis"]):::outdated
    x4b150ba8dbe4203d(["recorte_tif"]):::outdated ==> x75ae8feee719d1e2(["datos_gis"]):::outdated
    x0dc39fa9e42347ba>"reflectancia"]:::outdated ==> x75ae8feee719d1e2(["datos_gis"]):::outdated

  classDef outdated stroke:#FFC0CB,color:#FFFFFF,fill:#224289;
  classDef errored stroke:#FFC0CB,color:#FFFFFF,fill:#224289;
  classDef none stroke:#FFC0CB,color:#FFFFFF,fill:#224289;